name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0
