name: Clone Public Repository Workflow

on:
  push:
    branches:
      - main
      - build-autograding-process
  pull_request:
    branches:
      - main
      - build-autograding-process

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - name: test
        uses: ./
      
      - name: Access cloned repository content
        run: |
          echo "Ran the action"
